### PR TITLE
merge master to live-based branch

### PR DESCRIPTION
**Pull request by v-minnli**

### CODE REVIEW

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[9d391b8](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/9d391b8b02440572f2c246008b0dcadd400f33b1)_: 

:clock10: **Full build**: the average full build time is _22 min(s) 20 sec(s)_, this is based on the last _53_ build(s) for this repository.

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[9d391b8](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/9d391b8b02440572f2c246008b0dcadd400f33b1)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[.openpublishing.redirection.json](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/.openpublishing.redirection.json) | :white_check_mark:Succeeded | |
[README.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/README.md) | :white_check_mark:Succeeded | |
[azps-1.8.0/Az.ApiManagement/Update-AzApiManagementRegion.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.ApiManagement/Update-AzApiManagementRegion.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.apimanagement/update-azapimanagementregion?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Blueprint/New-AzBlueprintAssignment.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Blueprint/New-AzBlueprintAssignment.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.blueprint/new-azblueprintassignment?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/Add-AzImageDataDisk.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/Add-AzImageDataDisk.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/add-azimagedatadisk?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/Az.Compute.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/Az.Compute.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/index?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/New-AzImage.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/New-AzImage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/new-azimage?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/New-AzVM.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/New-AzVM.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/new-azvm?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/New-AzVmss.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/New-AzVmss.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/new-azvmss?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/Set-AzDiskImageReference.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/Set-AzDiskImageReference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/set-azdiskimagereference?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/Set-AzDiskUpdateDiskEncryptionKey.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/Set-AzDiskUpdateDiskEncryptionKey.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/set-azdiskupdatediskencryptionkey?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Compute/Set-AzSnapshotImageReference.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Compute/Set-AzSnapshotImageReference.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.compute/set-azsnapshotimagereference?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.DataLakeStore/Get-AzDataLakeStoreItemPermission.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.DataLakeStore/Get-AzDataLakeStoreItemPermission.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.datalakestore/get-azdatalakestoreitempermission?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.DataLakeStore/Restore-AzDataLakeStoreDeletedItem.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.DataLakeStore/Restore-AzDataLakeStoreDeletedItem.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.datalakestore/restore-azdatalakestoredeleteditem?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.FrontDoor/New-AzFrontDoorRoutingRuleObject.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.FrontDoor/New-AzFrontDoorRoutingRuleObject.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.frontdoor/new-azfrontdoorroutingruleobject?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.KeyVault/Set-AzKeyVaultAccessPolicy.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.KeyVault/Set-AzKeyVaultAccessPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.keyvault/set-azkeyvaultaccesspolicy?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Monitor/Set-AzActivityLogAlert.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Monitor/Set-AzActivityLogAlert.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.monitor/set-azactivitylogalert?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Network/New-AzApplicationGatewayFirewallPolicy.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Network/New-AzApplicationGatewayFirewallPolicy.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.network/new-azapplicationgatewayfirewallpolicy?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Network/New-AzNetworkSecurityGroup.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Network/New-AzNetworkSecurityGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.network/new-aznetworksecuritygroup?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Network/Remove-AzNetworkInterfaceTapConfig.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Network/Remove-AzNetworkInterfaceTapConfig.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.network/remove-aznetworkinterfacetapconfig?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.RecoveryServices/Get-AzRecoveryServicesAsrProtectionContainerMapping.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.RecoveryServices/Get-AzRecoveryServicesAsrProtectionContainerMapping.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.recoveryservices/get-azrecoveryservicesasrprotectioncontainermapping?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Sql/Add-AzSqlDatabaseToFailoverGroup.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Sql/Add-AzSqlDatabaseToFailoverGroup.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.sql/add-azsqldatabasetofailovergroup?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Sql/Az.Sql.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Sql/Az.Sql.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.sql/index?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Sql/Set-AzSqlServerActiveDirectoryAdministrator.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Sql/Set-AzSqlServerActiveDirectoryAdministrator.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.sql/set-azsqlserveractivedirectoryadministrator?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Sql/Update-AzSqlSyncSchema.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Sql/Update-AzSqlSyncSchema.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.sql/update-azsqlsyncschema?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Storage/Get-AzStorageUsage.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Storage/Get-AzStorageUsage.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.storage/get-azstorageusage?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-1.8.0/Az.Websites/Switch-AzWebAppSlot.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Websites/Switch-AzWebAppSlot.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/module/az.websites/switch-azwebappslot?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[azps-2.4.0/Az.ApplicationInsights/Remove-AzApplicationInsightsApiKey.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ApplicationInsights/Remove-AzApplicationInsightsApiKey.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.Automation/Register-AzAutomationDscNode.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.Automation/Register-AzAutomationDscNode.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.Blueprint/New-AzBlueprintAssignment.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.Blueprint/New-AzBlueprintAssignment.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.Blueprint/Publish-AzBlueprint.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.Blueprint/Publish-AzBlueprint.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.Blueprint/Set-AzBlueprintAssignment.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.Blueprint/Set-AzBlueprintAssignment.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Az.CognitiveServices.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Az.CognitiveServices.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccount.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccount.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountKey.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountKey.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountSku.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountSku.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountType.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountType.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountUsage.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Get-AzCognitiveServicesAccountUsage.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/New-AzCognitiveServicesAccount.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/New-AzCognitiveServicesAccount.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/New-AzCognitiveServicesAccountKey.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/New-AzCognitiveServicesAccountKey.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Remove-AzCognitiveServicesAccount.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Remove-AzCognitiveServicesAccount.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.CognitiveServices/Set-AzCognitiveServicesAccount.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.CognitiveServices/Set-AzCognitiveServicesAccount.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistry.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistry.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryCredential.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryCredential.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryReplication.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryReplication.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryWebhook.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryWebhook.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryWebhookEvent.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ContainerRegistry/Get-AzContainerRegistryWebhookEvent.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.ContainerRegistry/New-AzContainerRegistry.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ContainerRegistry/New-AzContainerRegistry.md) | :white_check_mark:Succeeded | |
[azps-2.4.0/Az.ContainerRegistry/New-AzContainerRegistryReplication.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-2.4.0/Az.ContainerRegistry/New-AzContainerRegistryReplication.md) | :white_check_mark:Succeeded | |

This comment lists only the first 50 files in the pull request.
For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C5%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201908050836442156-24%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nrpwwtVdhl%2FjTs%2FEDmdLNit7EVI7CiKak3WZ6ZMevEw%3D&st=2019-08-05T08%3A57%3A32Z&se=2019-09-05T09%3A02%3A32Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[ede31e5](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/ede31e51002e27526567bb2e993a7a5115751912)_: 

:clock10: **Full build**: the average full build time is _22 min(s) 7 sec(s)_, this is based on the last _54_ build(s) for this repository.

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[ede31e5](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/ede31e51002e27526567bb2e993a7a5115751912)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docfx.json](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docfx.json) | :white_check_mark:Succeeded | |
[docs-conceptual/azps-1.8.0/create-azure-service-principal-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/create-azure-service-principal-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/create-azure-service-principal-azureps?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/install-az-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/install-az-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/install-az-ps?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/manage-subscriptions-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/manage-subscriptions-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/manage-subscriptions-azureps?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/new-azureps-module-az.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/new-azureps-module-az.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/new-azureps-module-az?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/uninstall-az-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/uninstall-az-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/uninstall-az-ps?view=azps-1.8.0&branch=pr-en-us-24) (azps-1.8.0) |
[docs-conceptual/azps-2.5.0/create-azure-service-principal-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/create-azure-service-principal-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/create-azure-service-principal-azureps?view=azps-2.5.0&branch=pr-en-us-24) (azps-2.5.0) |
[docs-conceptual/azps-2.5.0/install-az-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/install-az-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/install-az-ps?view=azps-2.5.0&branch=pr-en-us-24) (azps-2.5.0) |
[docs-conceptual/azps-2.5.0/new-azureps-module-az.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/new-azureps-module-az.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/new-azureps-module-az?view=azps-2.5.0&branch=pr-en-us-24) (azps-2.5.0) |
[docs-conceptual/azps-2.5.0/using-experimental-modules.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/using-experimental-modules.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C5%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201908050838030495-24%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lA6JndMn6lcjK51iU2EHsMBdQEeB7O9XpVXMciadSAk%3D&st=2019-08-05T09%3A21%3A17Z&se=2019-09-05T09%3A26%3A17Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
