### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[0b5da66](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/0b5da660f4fa3903740b9da4b1055df8214804bf)_: 

:clock10: **Full build**: the average full build time is _22 min(s) 20 sec(s)_, this is based on the last _75_ build(s) for this repository.

**Comment by e2ebd7** [comment]
Docs Build status updates of commit _[0b5da66](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/0b5da660f4fa3903740b9da4b1055df8214804bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C1%5C6%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C202001060831535992-40%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=wew8PFgK%2Be91SVQ9RQbzGN30LM3KFrCWRlAClHcQsOE%3D&st=2020-01-06T08%3A58%3A34Z&se=2020-02-06T09%3A03%3A34Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd6** [comment]
Docs Build status updates of commit _[0b5da66](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/0b5da660f4fa3903740b9da4b1055df8214804bf)_: 

:clock10: **Full build**: the average full build time is _22 min(s) 22 sec(s)_, this is based on the last _77_ build(s) for this repository.

**Comment by e2ebd8** [comment]
Docs Build status updates of commit _[0b5da66](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/0b5da660f4fa3903740b9da4b1055df8214804bf)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2020%5C2%5C19%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C202002191621450182-40%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Vi2E7GQf2POsaHDaw522693W2rDigTXuTrdUJx1fIvE%3D&st=2020-02-19T16%3A47%3A56Z&se=2020-03-21T16%3A52%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
