### PR TITLE
Merge master into live-based

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[e908867](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/e9088678cd40834148e1b1165328ecbcf7d4a337)_: 

:clock10: **Full build**: the average full build time is _21 min(s) 54 sec(s)_, this is based on the last _57_ build(s) for this repository.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[e908867](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/e9088678cd40834148e1b1165328ecbcf7d4a337)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[azps-1.8.0/Az.Advisor/Az.Advisor.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Advisor/Az.Advisor.md) | :x:Error | | [Details](#user-content-a4a33bef-b8982d42)
[]() | :x:Error | | [Details](#user-content-b8982d42)
[docs-conceptual/azps-1.8.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/release-notes-azureps.md) | :bulb:Suggestion | | [Details](#user-content-c58b2b9c-b8982d42)
[docs-conceptual/azps-2.5.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/release-notes-azureps.md) | :bulb:Suggestion | | [Details](#user-content-2930681e-b8982d42)

<a id="a4a33bef-b8982d42"></a>
### [azps-1.8.0/Az.Advisor/Az.Advisor.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/azps-1.8.0/Az.Advisor/Az.Advisor.md)
 - **[Error]** `````Publishing of document 'azps-1.8.0/Az.Advisor/Az.Advisor.md' to document hosting service failed with asset id: module/az.advisor/index locale: en-us, depot name: MSDN.e2eprod-azureps, branch name: pr-en-us-27. Error: The client could not finish the operation within specified timeout.`````

<a id="b8982d42"></a>
###
 - **[Error]** `````An exception occurred during the build process. Please check the raw log and retry building your content again. If the issue persists, please open a ticket in http://SiteHelp and include the URL of publishing report as well as below information: One or more errors occurred..`````

<a id="c58b2b9c-b8982d42"></a>
### [docs-conceptual/azps-1.8.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/release-notes-azureps.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="2930681e-b8982d42"></a>
### [docs-conceptual/azps-2.5.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/release-notes-azureps.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C26%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201908260747499281-27%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=U3PUO%2Bp4YnaKXlO%2BAZOW1uJhE5sOxul%2BR8irwWi5Q6A%3D&st=2019-08-26T08%3A09%3A30Z&se=2019-09-26T08%3A14%3A30Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[e908867](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/e9088678cd40834148e1b1165328ecbcf7d4a337)_: 

:clock10: **Full build**: the average full build time is _21 min(s) 53 sec(s)_, this is based on the last _58_ build(s) for this repository.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[e908867](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/e9088678cd40834148e1b1165328ecbcf7d4a337)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs-conceptual/azps-1.8.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/release-notes-azureps.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/release-notes-azureps?view=azps-1.8.0&branch=pr-en-us-27) (azps-1.8.0) | [Details](#user-content-c58b2b9c-a05e7733)
[docs-conceptual/azps-2.5.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/release-notes-azureps.md) | :bulb:Suggestion | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/release-notes-azureps?view=azps-2.5.0&branch=pr-en-us-27) (azps-2.5.0) | [Details](#user-content-2930681e-a05e7733)
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |
[docfx.json](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docfx.json) | :white_check_mark:Succeeded | |
[docs-conceptual/azps-1.8.0/authenticate-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/authenticate-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/authenticate-azureps?view=azps-1.8.0&branch=pr-en-us-27) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/create-azure-service-principal-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/create-azure-service-principal-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/create-azure-service-principal-azureps?view=azps-1.8.0&branch=pr-en-us-27) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/install-az-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/install-az-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/install-az-ps?view=azps-1.8.0&branch=pr-en-us-27) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/manage-subscriptions-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/manage-subscriptions-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/manage-subscriptions-azureps?view=azps-1.8.0&branch=pr-en-us-27) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/new-azureps-module-az.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/new-azureps-module-az.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/new-azureps-module-az?view=azps-1.8.0&branch=pr-en-us-27) (azps-1.8.0) |
[docs-conceptual/azps-1.8.0/uninstall-az-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/uninstall-az-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/uninstall-az-ps?view=azps-1.8.0&branch=pr-en-us-27) (azps-1.8.0) |
[docs-conceptual/azps-2.5.0/authenticate-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/authenticate-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/authenticate-azureps?view=azps-2.5.0&branch=pr-en-us-27) (azps-2.5.0) |
[docs-conceptual/azps-2.5.0/create-azure-service-principal-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/create-azure-service-principal-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/create-azure-service-principal-azureps?view=azps-2.5.0&branch=pr-en-us-27) (azps-2.5.0) |
[docs-conceptual/azps-2.5.0/install-az-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/install-az-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/install-az-ps?view=azps-2.5.0&branch=pr-en-us-27) (azps-2.5.0) |
[docs-conceptual/azps-2.5.0/new-azureps-module-az.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/new-azureps-module-az.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/new-azureps-module-az?view=azps-2.5.0&branch=pr-en-us-27) (azps-2.5.0) |
[docs-conceptual/azps-2.5.0/using-experimental-modules.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/using-experimental-modules.md) | :white_check_mark:Succeeded | |
[docs-conceptual/azuredmps-0.9.0/overview.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azuredmps-0.9.0/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/deploymentmanager/overview?view=azuredmps-0.9.0-preview&branch=pr-en-us-27) (azuredmps-0.9.0-preview) |
[docs-conceptual/azurermps-2.5.0/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurermps-2.5.0/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azurerm/overview?view=azurermps-2.5.0&branch=pr-en-us-27) (azurermps-2.5.0) |
[docs-conceptual/azurermps-4.4.1/install-azurerm-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurermps-4.4.1/install-azurerm-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azurerm/install-azurerm-ps?view=azurermps-4.4.1&branch=pr-en-us-27) (azurermps-4.4.1) |
[docs-conceptual/azurermps-5.7.0/install-azurerm-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurermps-5.7.0/install-azurerm-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azurerm/install-azurerm-ps?view=azurermps-5.7.0&branch=pr-en-us-27) (azurermps-5.7.0) |
[docs-conceptual/azurermps-5.7.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurermps-5.7.0/release-notes-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azurerm/release-notes-azureps?view=azurermps-5.7.0&branch=pr-en-us-27) (azurermps-5.7.0) |
[docs-conceptual/azurermps-6.13.0/authenticate-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurermps-6.13.0/authenticate-azureps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azurerm/authenticate-azureps?view=azurermps-6.13.0&branch=pr-en-us-27) (azurermps-6.13.0) |
[docs-conceptual/azuresmps-4.0.0/install-azure-ps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azuresmps-4.0.0/install-azure-ps.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/servicemanagement/install-azure-ps?view=azuresmps-4.0.0&branch=pr-en-us-27) (azuresmps-4.0.0) |
[docs-conceptual/azurestackps-1.5.0/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurestackps-1.5.0/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azure-stack/overview?view=azurestackps-1.5.0&branch=pr-en-us-27) (azurestackps-1.5.0) |
[docs-conceptual/azurestackps-1.6.0/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurestackps-1.6.0/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azure-stack/overview?view=azurestackps-1.6.0&branch=pr-en-us-27) (azurestackps-1.6.0) |
[docs-conceptual/azurestackps-1.7.2/TOC.yml](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurestackps-1.7.2/TOC.yml) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azure-stack/overview?view=azurestackps-1.7.2&branch=pr-en-us-27) (azurestackps-1.7.2) |
[docs-conceptual/azurestackps-1.7.2/overview.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azurestackps-1.7.2/overview.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/azure-stack/overview?view=azurestackps-1.7.2&branch=pr-en-us-27) (azurestackps-1.7.2) |
[docs-conceptual/index.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/e2eprod-azureps/azure/index?branch=pr-en-us-27) |

<a id="c58b2b9c-a05e7733"></a>
### [docs-conceptual/azps-1.8.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-1.8.0/release-notes-azureps.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

<a id="2930681e-a05e7733"></a>
### [docs-conceptual/azps-2.5.0/release-notes-azureps.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/docs-conceptual/azps-2.5.0/release-notes-azureps.md)
 - **[Suggestion]** `````Missing attribute: author. Add the current author's GitHub ID. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````
 - **[Suggestion]** `````Missing attribute: title. Add a title string to show in search engine results. NOTE: This Suggestion will be elevated to a Warning on 9/1/2019.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C27%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201908270611514627-27%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=VXbbM9fIaNcdc%2BX9PIqn9AIbKuTfdyw2cJ5liePFM1A%3D&st=2019-08-27T06%3A31%3A21Z&se=2019-09-27T06%3A36%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[191667b](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/191667b1feb6528a2a1942078286aab3c7c661e2)_: 

:clock10: **Full build**: the average full build time is _21 min(s) 53 sec(s)_, this is based on the last _60_ build(s) for this repository.

**Comment by v-minnli** [comment]
Docs Build status updates of commit _[191667b](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/191667b1feb6528a2a1942078286aab3c7c661e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[.openpublishing.publish.config.json](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/master/.openpublishing.publish.config.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C8%5C27%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201908270802163007-27%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=T8FpnWl0RaFt2SWankaDkR%2FSUB2AM6uuI2xY6YKt4J0%3D&st=2019-08-27T08%3A20%3A42Z&se=2019-09-27T08%3A25%3A42Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
