### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[740a6e8](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/740a6e87bc420f27874056fdc71ba0efa1c23498)_: 

:clock10: **Full build**: the average full build time is _21 min(s) 52 sec(s)_, this is based on the last _65_ build(s) for this repository.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[740a6e8](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/740a6e87bc420f27874056fdc71ba0efa1c23498)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C14%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201910140738501413-34%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=qfs7FLOWlt0ynlGQjQVUQnrBCYyXE%2FJhtLeYn8MuX%2Bc%3D&st=2019-10-14T07%3A59%3A36Z&se=2019-11-14T08%3A04%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[740a6e8](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/740a6e87bc420f27874056fdc71ba0efa1c23498)_: 

:clock10: **Full build**: the average full build time is _21 min(s) 53 sec(s)_, this is based on the last _66_ build(s) for this repository.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[740a6e8](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/740a6e87bc420f27874056fdc71ba0efa1c23498)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C10%5C14%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201910140928150991-34%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=nfTdthXSW7G%2F07YL9T2g2NcO5AFe8kD3zFx47yY9zoQ%3D&st=2019-10-14T09%3A50%3A35Z&se=2019-11-14T09%3A55%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
