### PR TITLE
Don't Merge! Regression PR perf testing *with* metadata validation

### PR DESCRIPTION
**Pull request by OPSTestProduction**

### CODE REVIEW

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[662b483](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/662b4833d3ffc307f6581e83079ee519ce8cf105)_: 

:clock10: **Full build**: the average full build time is _22 min(s) 4 sec(s)_, this is based on the last _70_ build(s) for this repository.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[662b483](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/662b4833d3ffc307f6581e83079ee519ce8cf105)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C18%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201911180342595702-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=tNuokZwh4FTzimxzRaElRo2UUC%2BzMd4zpaRYf2%2FZ60s%3D&st=2019-11-18T04%3A07%3A11Z&se=2019-12-19T04%3A12%3A11Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-Docs** [comment]
Docs Build status updates of commit _[662b483](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/662b4833d3ffc307f6581e83079ee519ce8cf105)_: 

:clock10: **Full build**: the average full build time is _22 min(s) 7 sec(s)_, this is based on the last _71_ build(s) for this repository.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[662b483](https://github.com/OPS-E2E-Prod/azure-docs-powershell/commits/662b4833d3ffc307f6581e83079ee519ce8cf105)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[TestingPullRequest.md](https://github.com/OPS-E2E-Prod/azure-docs-powershell/blob/prtest/TestingPullRequest.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C11%5C18%5Cc70f669d-c188-9da4-ea35-7cd3851e9fb0%5CPullRequest%5C201911180709522305-36%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Hl62Cnv%2B6dSUWfztE46wPWY0AqKV9ZFsGYUT9M380xQ%3D&st=2019-11-18T07%3A34%3A00Z&se=2019-12-19T07%3A39%3A00Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
